import { chromium } from 'playwright';
const [url, yStr, out] = process.argv.slice(2);
const b = await chromium.launch({ args: ['--disable-gpu', '--disable-dev-shm-usage', '--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 1400, height: 1100 } })).newPage();
await p.goto(url, { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.addStyleTag({ content: 'html{scroll-behavior:auto !important}' });
await p.waitForTimeout(4000);
await p.evaluate((y) => window.scrollTo({ top: y, behavior: 'instant' }), parseInt(yStr));
await p.waitForTimeout(1800);
await p.screenshot({ path: out });
console.log('captured at scroll', yStr, '->', out);
await b.close();
